### PR TITLE
Random Quote Generator using HTML, CSS and Javascript

### PR DESCRIPTION
**Pull request by amanullahmd12**
## **Add the working demo (screen recording) below _(Required)_**

https://github.com/anishaswain/Simple-JS-Projects/assets/92320933/71d1f2ac-f3da-443a-8c09-4ba73b4c913a

Screenshot 2023-10-02 at 12 17 04 AM

## Describe your changes
Completed Random Quote Generator using HTML, CSS and Javascript and use https://api.quotable.io/random API for fetching the quote.

## Issue ticket number and link

Create a Javascript app for Random Quote Generator #3

https://github.com/anishaswain/Simple-JS-Projects/issues/3

## Checklist before requesting a review
- [Done ] I have performed a self-review of my code
- [Done] I have added issue number to the PR.
- [Done ] I have added screen recording of the working app.

### CODE REVIEW

**Comment by anishaswain** [comment]
@amanullahmd12 inside project2 folder, please create another folder named amanullahmd12 and then inside that folder add your html/css/js files

**Review by anishaswain — CHANGES_REQUESTED** [review]
Please remove /DS_Store file from Project 6

**Comment by amanullahmd12** [comment]
@anishaswain  Done. Kindly check it. Sorry for the inconvenience.

**Comment by anishaswain** [comment]
> @anishaswain Done. Kindly check it. Sorry for the inconvenience.

There is still one file remaining. Kindly double check

**Pull request closed without merging**
